### ISSUE TITLE
cli cache:flush throws 401 - when using BasicAuth protection

### ISSUE THREAD

**Issue by boi1** [litespeedtech/magento2-LiteSpeed_LiteMage#34]
We use the LiteSpeed/LiteMage extenion in version 2.1.9, 

we added the cache also on a staging enviroment where a 
**.htaccess BasicAuth** protection is in place: 

When using the cli command `bin/magento cache:flush`, we get the following output: 

```
<!DOCTYPE html>
<html style="height:100%">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<title> 401 Unauthorized
</title></head>
<body style="color: #444; margin:0;font: normal 14px/20px Arial, Helvetica, sans-serif; height:100%; background-color: #fff;">
<div style="height:auto; min-height:100%; ">     <div style="text-align: center; width:800px; margin-left: -400px; position:absolute; top: 30%; left:50%;">
        <h1 style="margin:0; font-size:150px; line-height:150px; font-weight:bold;">401</h1>
<h2 style="margin-top:20px;font-size: 30px;">Unauthorized
</h2>
<p>Proper authorization is required to access this resource!</p>
</div></div></body></html>

Flushed cache types:
config
layout
block_html
collections
reflection
db_ddl
compiled_config
eav
customer_notification
config_integration
config_integration_api
full_page
target_rule
config_webservice
translate
```

when we remove the BasicAuth from the .htaccess we get the expected result. for the command `bin/magento cache:flush`

```
LiteMage purged tags *
Flushed cache types:
config
layout
block_html
collections
reflection
db_ddl
compiled_config
eav
customer_notification
config_integration
config_integration_api
full_page
target_rule
config_webservice
translate
```

**Comment by Eddcapone** [comment]
Any news on this?

**Comment by litespeedtech** [comment]
If you really have to enable this protection, the only solution is to add the password config in litemage config. so it can send out the curl request with proper password. However, this will expose the password. do you like this solution? In order to purge litemage, it will send out a curl request with same user and password. We can probably set the input field as password, so you can input/update, cannot see the real value once saved.

**Comment by Eddcapone** [comment]
Where do we find the litemage config? Can we do this ourselve or does it need a ticket to our hoster / litemage?

**Comment by lonesome-dev** [comment]
> If you really have to enable this protection, the only solution is to add the password config in litemage config. so it can send out the curl request with proper password. However, this will expose the password. do you like this solution? In order to purge litemage, it will send out a curl request with same user and password. We can probably set the input field as password, so you can input/update, cannot see the real value once saved.

This also happens on a Store whitout Basic-Auth, when Magento is in maintenance-mode and cache:flush is triggered. 

How is it handled in this situation?

**Comment by litespeedtech** [comment]
@Eddcapone I figured out a way to set in litemage config for user:password in obscure field. will do a new release this week to address this.
@lonesome-dev when store in maintenance mode, I can skip the cli flush to avoid this error message. you will need to go to admin to flush from browser.

**Comment by lonesome-dev** [comment]
> @lonesome-dev when store in maintenance mode, I can skip the cli flush to avoid this error message. you will need to go to admin to flush from browser.

I think you misunderstood the problem. When we start deployments, the store is set into maintenance-mode and the neccessary compiling commands like setup:upgrade, cache:flush etc. where sent in CLI. Litespeed then throws a 401 at the cache:flush-Step. Currently we have to disable maintenance-mode and trigger cache:flush again.

Is there a setting, to avoid the error message in maintenance-mode, so that the cache is flushed successfully?

**Comment by litespeedtech** [comment]
Yes, just add your localhost IP to maintenance allowed ips. I'll make a new release to show this message.

**Comment by litespeedtech** [comment]
This should be resolved with v2.2.3 release.

**Comment by lonesome-dev** [comment]
Hey, thanks for your quick fix.

Basic Auth settings + cache:flush are no longer showing the error.

The other problem with maintenance-mode still exists.
If I do `bin/magento maintenance:enable --ip=XXX` and execute `bin/magento setup:upgrade` following will show up:

`Cache types config flushed successfully
Flush LiteMage Cache by cli -  Unexpected HTTP code: 503
Cache cleared successfully
File system cleanup:
...
Updating modules:
Flush LiteMage Cache by cli -  Unexpected HTTP code: 503
Cache cleared successfully
Schema creation/updates:
...
`
Is it possible to fix this too?

**Comment by litespeedtech** [comment]
CLI will issue HTTPS request, which is blocked by the maintenance mode. So the IP you add needs to be the server IP that shows in the access log. have you tried 127.0.0.1?

**Comment by gntlby** [comment]
Hello,
When I want to clear cache after v2.2.3 version,

php bin/magento c:f 
Flush LiteMage Cache by cli -  Unexpected HTTP code: 302

is this normal?

Thanks.

**Comment by lonesome-dev** [comment]
> CLI will issue HTTPS request, which is blocked by the maintenance mode. So the IP you add needs to be the server IP that shows in the access log. have you tried 127.0.0.1?

Worked like expected, thanks!
